theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Welcome to my portfolio, my name is Leonardo Sanchez, and  I am a Level Designer. 
I only have three completed games that you can browse and try out yourself if you wish. 
I am well versed in C#, but I am more skilled in designing terrific levels for various different games.
logo: 
