theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Introduction to programing
Logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F768708230121263226%2F&psig=AOvVaw3Wra_xPaAugVIFZZbCNH_J&ust=1636139984815000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOjx4s62__MCFQAAAAAdAAAAABAP
