theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Introduction to programing
Logo: ![gamerdash_gif_by_dori_to-d5rf67a](https://user-images.githubusercontent.com/91509500/140406640-d013feb2-9535-4bd6-bc24-76dec184f1df.gif)
