theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Introduction to programing
logo: ![GitHub Logo](https://raw.githubusercontent.com/epicLeo2101/epicLeo2101.github.io/main/gamerdash_gif_by_dori_to-d5rf67a.gif)
