theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Welcome to my portfolio, my name is Leonardo Sanchez, and  I am a Level Designer. I only have three completed games that you can browse and try out yourself if you wish. I am well versed in C#, but I am more skilled in designing terrific levels for various different games.
logo: https://media.discordapp.net/attachments/1003132081121021983/1080974930809725079/20210610_094407.jpg?width=457&height=609
