theme: jekyll-theme-minimal
tittle: Leonardo Sanchez
description: Introduction to programing
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.deviantart.com%2Fdori-to%2Fart%2FGamerdash-gif-348388390&psig=AOvVaw2niM955bflsXqxhfhHVTbA&ust=1636139637767000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNCquaK1__MCFQAAAAAdAAAAABAD
