theme: jekyll-theme-minimal
title: Leonardo Sanchez
description: Introduction to programing
Logo: ![16c226b3de9d94d4ec6fada7cc767281--my-little-pony-friendship-rainbow-dash](https://user-images.githubusercontent.com/91509500/140407115-0087f00d-cd37-4a0c-9cf2-fbbf3a58ed36.jpg)
